version: '3.7'
services:
  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - webserver

  php:
    build:
      context: ./bsi-php
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
    networks:
      - webserver


networks:
  webserver:
    driver: bridge
    internal: true
