version: '3.7'
services:
  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/mysql
    restart: on-failure
    networks:
      - webserver

  php:
    build:
      context: ./bsi-php
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
    restart: on-failure
    networks:
      - webserver

  nginx:
    build:
      context: ./bsi-nginx
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
    restart: on-failure
    networks:
      - webserver
      - public
    ports:
      - "8000:80"
    depends_on:
      - php
      - mariadb

networks:
  webserver:
    driver: bridge
    internal: true
  public:
    driver: bridge

